[build]
  command = "npm run build"
  publish = "."
  environment = { NEXT_PUBLIC_STRAPI_URL = "your_api_url" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "www.ventratech.co.za/*"
  to = "https://ventratech.co.za/:splat"
  status = 301
  force = true
