[build]

  
  environment = { NEXT_PUBLIC_STRAPI_URL = "https://trusty-chicken-b252799906.strapiapp.com" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "www.ventratech.co.za/*"
  to = "https://ventratech.co.za/:splat"
  status = 301
  force = true
