[build]
  command = "npm run build"
  publish = ".next"
  environment = { 
    NEXT_PUBLIC_STRAPI_URL = "https://trusty-chicken-b252799906.strapiapp.com" 
  }

[[plugins]]
  package = "@netlify/plugin-nextjs"
